import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,

  {
    rules: {
      // Standard convention: a leading underscore marks an intentionally unused
      // binding. Needed for mock signatures that must declare a parameter to be
      // type-compatible without using it.
      "@typescript-eslint/no-unused-vars": [
        "error",
        {
          argsIgnorePattern: "^_",
          varsIgnorePattern: "^_",
          caughtErrorsIgnorePattern: "^_",
        },
      ],
    },
  },
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",

    // Generated code — NOT hand-written, regenerated by `prisma generate` on
    // every install. Linting it produced ~660 errors that no human can act on
    // and that would reappear after any regeneration. Excluded deliberately so
    // that lint failures always indicate a real problem in application code.
    // Reviewed as part of Phase D; see docs/SECURITY_AND_QUALITY.md.
    "src/lib/generated/**",

    // Build/tooling output
    "coverage/**",
    ".vercel/**",
    "node_modules/**",
  ]),
]);

export default eslintConfig;
